package io.github.fpxli.wine_manager.domain.enums;

public enum TipoComida {
    //ENTRADAS
    SALADA_VERDE,
    SALADA_COM_FRUTAS,
    SOPA_CREMOSA_LEGUMES,
    SOPA_CREMOSA_QUEIJO,
    CALDO,

    // CARNES
    CARNE_VERMELHA_GRELHADA,
    CARNE_VERMELHA_MAGRA,
    CARNE_VERMELHA_GORDUROSA,
    CARNE_DE_PORCO,
    CARNE_DE_CACA,
    AVES_ASSADAS,
    AVES_DE_CACA,

    // MASSAS
    MASSA_MOLHO_TOMATE,
    MASSA_MOLHO_BRANCO,
    MASSA_FRUTOS_DO_MAR,
    MASSA_FUNGHI,

    // QUEIJOS
    QUEIJO_AZUL,
    QUEIJO_DURO_CURADO,
    QUEIJO_MOLE_FRESCO,
    QUEIJO_MACIO_MATURADO,

    // MAR E ORIENTAL
    PEIXE_BRANCO_GRELHADO,
    PEIXE_GORDO,
    SUSHI_E_SASHIMI,
    FRUTOS_DO_MAR_GORDUROSOS,

    //VEG
    VEGETAIS_GRELHADOS,
    LEGUMES_ASSADOS,
    COGUMELOS_MANTEIGA,

    // SOBREMESAS
    SOBREMESA_CHOCOLATE,
    SOBREMESA_FRUTAS_CITRICAS,
    SOBREMESA_FRUTAS_DOCES,
    SOBREMESA_A_BASE_DE_LEITE,
    SOBREMESA_OVOS
}
